version: 0.2
phases:
  pre_build:
    commands:
      - echo Login into Amazon ECR started on `date`
      - aws --version
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 038462751546.dkr.ecr.us-east-2.amazonaws.com
      - echo "Setting repository URI..."
      - REPOSITORY_URI=038462751546.dkr.ecr.us-east-2.amazonaws.com/cicd
      - echo "Setting image tag..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Build and tagging started image on `date`"
      - echo "running mvn clean install..."
      - mvn clean install
      - echo "Building docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - echo "Tagging the Docker image..."
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "pushing docker image to Amazon ECR started on `date`"
      - echo "Pushing to repository..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "setting container name..."
      - DOCKER_CONTAINER_NAME=cicd
      - echo "Writing image definitions file..."
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing image definitions file
      - cat imagedefinitions.json
artifacts:
    files:
      - imagedefinitions.json